language: python

matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11    # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS

install:
  - pip3 install --upgrade pip  # all OSes agree about 'pip3'
  - pip install -r requirements.txt

# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
script: python3 wsgi.py

deploy:

